### ISSUE TITLE
似乎在Android O上无法使用

### ISSUE THREAD

**Issue by imliuruiqi** [loveyu/WifiPwd#1]
可能是由于Android O默认启用了设备加密吗？

**Comment by loveyu** [comment]
可能性不大吧，除非文件路径做了调整。我最近没看过这个问题，找时间看看

**Comment by charshine** [comment]
一加5升级至android O后无法查看，显示请重新root。确定已有root权限

**Comment by loveyu** [comment]
@imliuruiqi @charshine 刚针对 Android O 做了调整，由于文件变化了导致
新路径为 /data/misc/wifi/WifiConfigStore.xml
